import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning={true}
      >
        <nav className="text-2xl">
          <Link href={'/'}>Todo</Link>
          <Link style={{ marginLeft: '10px' }} href={'/posts'}>
            Post
          </Link>
          <Link className="ml-[10px]" href={'/board'}>
            Board
          </Link>
          <Link className="ml-[10px]" href={'/parallelBoard'}>
            Parallel_Board
          </Link>
          <Link className="ml-[10px]" href={'/parallelBoard/settings'}>
            Parallel_Board_Settings
          </Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  )
}
